databases:
  - name: arcticxpressdb
    plan: free
    databaseName: arcticxpress
    user: arcticxpress

services:
  - type: web
    plan: free
    name: arcticxpress
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn cargo.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: arcticxpressdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
